project:
  type: book
  output-dir: /home/kazuo/public_html/CAMCA_archive #docs
book:
  title: "CA/MCA関連のスライド、論考集"
  author: "藤本一男"
  date: "2025/11/18"
  chapters:
    - index.qmd
#    - intro.qmd
    - chap1.qmd # SSJDA計量分析セミナースライド
    - chap2.qmd # 対応分析研究会スライド
    - chap3.qmd # 津田塾大学紀要、CARME
    - chap4.qmd # MCAの応用。NLP、NICT
    - chap5.qmd # 可視化Tools
    - chap6.qmd # CA/MCA関連解約
#    - biblio.qmd
#    - note.qmd
#    - rireki.qmd
#    - summary.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: #United #cosmo
      light: flatly
      dark: darkly
    cover-image: CAiP3cover.png #summer2025.png
  pdf:
    documentclass: bxjsbook
    classoption: xelatex,ja=standard,a4paper
    editor: visual
    keep-tex: true
    toc: true  # 目次を有効にする（お好みで）

#prefer-html: true

document:
  toc-own-page: true  # 目次を新しいページにする（お好みで）
